### ISSUE TITLE
Download original TIFFs.

### ISSUE THREAD

**Issue by edsu** [umd-mith/fla-web#21]
Would be useful to be able to download tiffs.

**Comment by trevormunoz** [comment]
What's the use case for this? Data sharing/reuse?

**Comment by edsu** [comment]
I wasn't actually sure why Peter wanted this. Worth double checking before doing too much work on it. I guess it would require keeping the TIFFs online, and that would add an additional cost.

**Comment by edsu** [comment]
We can reopen if we need to revisit this.
